### ISSUE TITLE
Authentication ?

### ISSUE THREAD

**Issue by jothoma1** [larsks/ldap2json#1]
Hi,
thanks for this great projet, i'm really interested. 
Is it possible to add an authentication when connecting to ldap ? 
My ldap servers are using auth & ldaps and for now it doesnt work
Thanks for your help

**Comment by larsks** [comment]
> Is it possible to add an authentication when connecting to ldap ?

It's certainly possible, but given the age of the project (2012!) and the fact that I'm no longer interacting with an ldap server on a regular basis I'm probably not going to make any changes. There may more recent and better maintained solutions out there.

If you wanted to try adding the support yourself it should be too hard:

- Add support for reading an authentication DN and password from the configuration file
- Add a call to `simple_bind` after the call to `ldap.initialize` to perform the authentication.

There are some examples [here](http://www.programcreek.com/python/example/3267/ldap.initialize), and of course the documentation for the ldap module is [here](https://www.python-ldap.org/doc/html/index.html).
